baseURL = 'https://furycd001.github.io/'
languageCode = 'en-us'
title = 'd:tour'
theme = 'mnml'
paginate = 8

[params]
social = [
  { name = "github", url = "https://github.com/furycd001" },
  { name = "dotfiles", url = "https://github.com/furycd001/dots" },
  { name = "mastodon", url = "https://fosstodon.org/@Furycd001" },
  { name = "email", url = "mailto:jonnybowes2000@googlemail.com" },
  { name = "donate", url = "https://paypal.me/furycd001?country.x=GB&locale.x=en_GB" }
]

# Enable RSS
rss = true